### ISSUE TITLE
Thanks! and `@NgModule annotation` error

### ISSUE THREAD

**Issue by thefliik** [gethinoakes/ngx-masonry#1]
Thanks **_so_** much for publishing your patches to `angular2-masonry`!!!

FYI, when I installed your package from npm (without issue) and tried to import the `NgxMasonryModule` into an Angularv5.0.3 project, I received an

```
ERROR in Error: Unexpected value 'NgxMasonryModule in /project_root/node_modules/ngx-masonry/src/ngx-masonry.module.js' imported by the module 'PersonModule in /project_root/apps/coordination/src/app/person/person.module.ts'. Please add a @NgModule annotation
```

I decided to just download your repo, build it like a personal library in my project, and access it normally, and everything works fine.

**Comment by gethinoakes** [comment]
No problem! Happy to see people have found it 🙂

That's interesting though, as I had a friend try it out and it worked fine for them. Did you import it into your App module? I see in the error it seems to be imported into a sub feature module, this is the only thing I can think that would cause the error. Though I'll do some testing when I have chance.

Also, did you have any problems with the styles? I meant to add to do the documentation that you need to the following css for the masonry layout to work properly

```
ngx-masonry {
  display: block !important;
}
```

**Comment by thefliik** [comment]
I just tested, and I run into the same issue when importing the package into my root `app.module.ts`

```
ERROR in Error: Unexpected value 'NgxMasonryModule in /project_root/node_modules/ngx-masonry/ngx-masonry.js' imported by the module 'AppModule in /project_root/apps/coordination/src/app/app.module.ts'. Please add a @NgModule annotation.
```

I'm using [nrwl/nx](https://nrwl.io/nx/guide-getting-started), which may be complicating matters, though I don't see why it would.

Also ya, I had noticed he `display: block` issue.

**Comment by juhguu** [comment]
I have the same error. On ng build --prod with Angular Universal.

**Comment by thefliik** [comment]
@juhguu you can get around the error by downloading the source and building the module in your project locally.

**Comment by gethinoakes** [comment]
@thefliik @juhguu 
fixed in https://github.com/gethinoakes/ngx-masonry/releases/tag/v1.0.0
