### ISSUE TITLE
horizontalOrder not working

### ISSUE THREAD

**Issue by hmanprod** [gethinoakes/ngx-masonry#1]
horizontalOrder seems to not working

**Comment by gethinoakes** [comment]
... any errors, example code, live example of your issue?

**Comment by hmanprod** [comment]
I have no error on my console.
The feature horizontalOrder: true is only not working. My items is not order from left to rigth as it supposed to do as explain [here](https://github.com/desandro/masonry/issues/873):

Here below my code

```
<ngx-masonry [options]="configMasonry">
       <ngxMasonryItem class="brick" *ngFor="let article of notes">
        <div class="card">
		<single-card
		[article]="article"
		[currentUser]="currentUser"
		[readModal]="readModal"
		[signalerModal] = "signalerModal"></single-card>
	</div>
      </ngxMasonryItem>
</ngx-masonry>
------------------------------------
configMasonry: MasonryOptions = {
  itemSelector: '.brick',
  horizontalOrder: true
};
```

**Comment by hmanprod** [comment]
I got it. I need to update to the last version of masonry-layout to make it work correctly : 4.2.0 to 4.2.1

**Comment by kanvishok** [comment]
@hmanprod I updated to 4.2.2 also still horizontalOrder not correct always. its 70% to 80% of the time. I am not sure if I am missing 

<ngx-masonry [useImagesLoaded]="true" [options]="masonryOptions" >
  <ngxMasonryItem   *ngFor="let feed of  this.feeds.ToArray()" class="brick">
    <app-feed-card [feed]="feed"  ></app-feed-card> 
  </ngxMasonryItem>
</ngx-masonry>

 public masonryOptions: NgxMasonryOptions  = {
    itemSelector: '.brick',
    
    horizontalOrder: true,
  };

**Comment by pranayg25** [comment]
@hmanprod How did you update the version? can you please explain? I am still struggling with this.

**Comment by ifumi** [comment]
I got the same problem. The horizontalOrder property seems to do nothing. Each time I reload the page, the order of the items is different.

**Comment by wynfred** [comment]
https://github.com/wynfred/ngx-masonry/issues/38#issuecomment-629088124
