### ISSUE TITLE
How to use it with percent width?

### ISSUE THREAD

**Issue by asfo** [gethinoakes/ngx-masonry#10]
Hi, I'm trying to use it in my project, I work with Foundation 6.3.1 which use percent in widths.

I tried to do something like:
```
<ngx-masonry class="row" [options]="{ columnWidth: '.large-6', itemSelector: '.large-6' }">
<ngx-masonry-item class="large-6">Hello!</ngx-masonry-item>
</ngx-masonry>
```

But it didn't work, anyone knows how can I make it to work?. 

Thanks for your help

**Comment by thefliik** [comment]
You need to use a grid sizer as explained in the [masonry docs](https://masonry.desandro.com/layout.html) (response layout section). Took me a while to get things working the first time, but I have a 2 column responsive layout working (though all my grid items have the same width).

Note: your grid sizer needs to be inside `<masonry></masonry>`

**Comment by asfo** [comment]
I tried with:
```
<div class="row expanded">
      <ngx-masonry [options]="{ columnWidth: '.large-6', itemSelector: '.columns', percentPosition: true }">
            <ngx-masonry-item class="large-6 columns">Hello</ngx-masonry-item>
            <ngx-masonry-item class="large-6 columns">Hello</ngx-masonry-item>
      </ngx-masonry>
</div>
```

Basically `row expanded` is a width: 100% container.
And `large-6` is a width: 50% responsive.

And still not working ...

I tried doing "the same" but without angular, on CodePen:
https://codepen.io/asfo/pen/WdYvNp

And works...

I don't know if I'm doing something wrong with the nx-masonry-item or what.

Note: I don't include the "grid sizer" like the example on the masonry page does, but I did it without it in the CodePen and still working, anyways I tried with the grid-sizer inside the `<ngx-masonry>...` too but didn't work.

**Comment by thefliik** [comment]
This works for me
```
<ngx-masonry [options]="{columnWidth: '.masonry-column-sizer', gutter: 24, percentPosition: true,  transitionDuration: '0'}">
  <div class='masonry-column-sizer'></div>
  <ngx-masonry-item>
    <person-basic-info-tile [person]="person" [cannotEdit]='cannotEdit'></person-basic-info-tile>
  </ngx-masonry-item>
  <ngx-masonry-item>
    <person-contact-info-tile [person]="person" [cannotEdit]='cannotEdit'></person-contact-info-tile>
  </ngx-masonry-item>
</ngx-masonry>
```
with styles:
```
:host {
  display: block;
  overflow-y: auto;
}

ngx-masonry {
  display: block;
  height: 100%;
  width: 100%;
}

ngx-masonry-item, .masonry-column-sizer {
  width: calc(50% - 12px);
}
```

**Comment by asfo** [comment]
I tried with your styles and with your code but still doesn't works.

Here is a demo:
![demo](https://i.imgur.com/lV3vTti.png)
https://i.imgur.com/lV3vTti.png

I don't know why the jquery plugin works very well in the codepen but in angular is not working and I'm using the "same code" (same options, same style...)

**Comment by gethinoakes** [comment]
Not an issue with the library it seems but with your implementation of the masonry options? closing.

**Comment by asfo** [comment]
Mmm yeah, not an issue with the library but using the library breaks everything but without it, works as intended...

**Comment by gethinoakes** [comment]
That was quite a contradictory sentence...
Anyway it's not the library as @thefliik had it working using it, and I have also used PercentPosition in the past with it (don't anymore). And using the library doesn't "break everything" as I've been using it for months. 

Don't know why it isn't for you.

**Comment by jorroll** [comment]
Note, it looks like the code expects a boolean value for `updateLayout`, but, while assigning a new boolean to the property would trigger change detection the first time, reassigning the same value boolean to the property would not trigger change detection subsequent times.

**Comment by jayzyaj** [comment]
@thefliik  I tried to do that earlier in this example below.

```
@ViewChild('masonry') masonry: NgxMasonryComponent

events.subscribe('community-post-ongoing:created-successfully', (data) => {
      const promise = Promise.resolve(data);
      promise.then(res => {
        this.loadingBar.complete()
        const post = { ...res, loaded: false }
        this.posts.unshift(post)
        setTimeout(() => {
          this.posts[0].loaded = true
          this.masonry.layout()
        }, 2000)
      })
    });

```
And in my html

```
<ngx-masonry #masonry [options]="myOptions" [useImagesLoaded]="true" class="masonry-grid" [updateLayout]="posts">
<ngxMasonryItem class="masonry-item col-6" *ngFor="let post of posts">
```

For more clarification I used the **object spread oberator** and add a property of `loaded: false`  when I get the response of the newly created post. When the loaded is set to **false** it will show a preloader animation in that single object in the array that I created using html and css. The rest of the array should not reload which means all **object** in the **old array** has an `loaded` property that is already have been set to **true** and I just want them to adjust from left to right to the bottom so that the new array position is at the right top which I can't achieve it.

**Comment by wynfred** [comment]
Not sure if this helps your issue, just don't forget to use reload_items if you change the order of the array.
https://github.com/wynfred/ngx-masonry/issues/18#issuecomment-520551876
