### ISSUE TITLE
@NgModule annotation error

### ISSUE THREAD

**Issue by shad1w** [gethinoakes/ngx-masonry#21]
In the latest version, I'm having the same problem as mentioned in the closed issue #1.

It seems like in the published NPM package, the `@NgModule` annotation is missing in `ngx-masonry.module.d.ts` again.

**Comment by darthsitthiander** [comment]
I'm getting the same error message. Hopefully this is a quick fix seeing as it had been resolved earlier.

**Comment by Lxxyx** [comment]
Same issue

**Comment by alexkovachevic** [comment]
I'm getting this error: 

ERROR in Error during template compile of 'NgxMasonryModule'
  Function calls are not supported in decorators in 'NgModule'
    'NgModule' calls a function at ../@angular/core/core.ts(194,50).

**Comment by AhHa45** [comment]
I have the same issue:
    "@angular/core": "^5.2.10",

**Comment by gethinoakes** [comment]
Will fix in #28
