### ISSUE TITLE
"ngx-masonry": "^1.0.7" Missing horizontalOptions

### ISSUE THREAD

**Issue by cgilbe27** [gethinoakes/ngx-masonry#23]
ERROR in Z:/WildFyre/webcl/src/app/userPosts/userPosts.component.ts (19,5): Type '{ transitionDuration: string; horizontalOrder: boolean; }' is not assignable to type 'NgxMasonryOptions'.
  Object literal may only specify known properties, and 'horizontalOrder' does not exist in type 'NgxMasonryOptions'.

Latest npm package has the following NgxMasonryOptions:
http://prntscr.com/j8f3jg

**Comment by cgilbe27** [comment]
Was able to fix this by adding the code directly into my project and adding the horizontalOrder?: boolean; param to the end of ngx-masonry-options.interface.ts

**Comment by gethinoakes** [comment]
Thanks for reporting, will fix in #28
