### ISSUE TITLE
Using images loaded can't load in order

### ISSUE THREAD

**Issue by brettshepherd** [gethinoakes/ngx-masonry#25]
I'm new to this library, so I don't know if this is really a bug as much as just a limitation, but how can i make the images actually appear in order when using the useImagesLoaded. They are usually just completely mixed. I tried taking a look at the source code, but to be honest didn't really know what to add/change. Any ideas?

**Comment by gethinoakes** [comment]
Images load in the order that they load from the server, depending on their size etc. If you look at the ImagesLoaded library you'll see the same thing.

If you wanted to show them in order you would need to write a script that would delay showing each image until the previous image had loaded.

**Comment by wynfred** [comment]
Hi, could you create an example on stackblitz that reproduces this issue? And you can also check how long does it take to load the gif without masonry.
