### ISSUE TITLE
Support Angular 6 by upgrading package dependencies?

### ISSUE THREAD

**Issue by valorad** [gethinoakes/ngx-masonry#26]
When implementing ngx-masonry to my project, I encountered an error:

> ERROR in node_modules/ngx-masonry/node_modules/@angular/core/src/change_detection/differs/default_iterable_differ.d.ts(5,5): error TS2416: Property 'create' in type 'DefaultIterableDifferFactory' is not assignable to the same property in base type 'IterableDifferFactory'.
> ....

I am working on a project involving Angular 6.

I noticed that ngx-masonry has dependencies of `@angular/core^4.x.x`, so i tried deleting `node_modules` folder in ngx-masonry package (so as to use my Angular 6), and compilation was successful.

So I assume we can just upgrade the dependencies to 6? Or at least add as a peer dependency?

**Comment by gethinoakes** [comment]
Yeah.

I've just started upgrading the angular project I work on day to day to Angular 6 and they have a nice new feature where you can build a library inside the project and publish it, so I'll be doing that soon for this library and hopefully that'll fix a bunch of issues people have been raising as well as yours.

**Comment by gethinoakes** [comment]
Closing for #28
