### ISSUE TITLE
Uncaught Error: Unexpected value 'NgxMasonryModule' imported by the module 'AppModule'. Please add a @NgModule annotation.

### ISSUE THREAD

**Issue by LucHighwalker** [gethinoakes/ngx-masonry#27]
Hey, so I'm getting this error when trying to import the module, it just flat out fails to compile. This is before even trying to use it, just importing it into the app.module results in this error. I am using angular 5. I have tried saving it to a local folder instead of as an npm module as others who are failing to get it to compile have suggested, but it still throws the same errors. I'm not entirely sure what they mean, but hopefully it helps you out.

> compiler.js:486 Uncaught Error: Unexpected value 'NgxMasonryModule' imported by the module 'AppModule'. Please add a @NgModule annotation.
>     at syntaxError (compiler.js:486)
>     at eval (compiler.js:15240)
>     at Array.forEach (<anonymous>)
>     at CompileMetadataResolver.getNgModuleMetadata (compiler.js:15215)
>     at JitCompiler._loadModules (compiler.js:34413)
>     at JitCompiler._compileModuleAndComponents (compiler.js:34374)
>     at JitCompiler.compileModuleAsync (compiler.js:34268)
>     at CompilerImpl.compileModuleAsync (platform-browser-dynamic.js:239)
>     at PlatformRef.bootstrapModule (core.js:5578)
>     at eval (main.ts:11)
> syntaxError @ compiler.js:486
> (anonymous) @ compiler.js:15240
> CompileMetadataResolver.getNgModuleMetadata @ compiler.js:15215
> JitCompiler._loadModules @ compiler.js:34413
> JitCompiler._compileModuleAndComponents @ compiler.js:34374
> JitCompiler.compileModuleAsync @ compiler.js:34268
> CompilerImpl.compileModuleAsync @ platform-browser-dynamic.js:239
> PlatformRef.bootstrapModule @ core.js:5578
> (anonymous) @ main.ts:11
> ./src/main.ts @ main.bundle.js:442
> __webpack_require__ @ inline.bundle.js:55
> 0 @ main.bundle.js:450
> __webpack_require__ @ inline.bundle.js:55
> webpackJsonpCallback @ inline.bundle.js:26
> (anonymous) @ main.bundle.js:1
> client:147 [WDS] Warnings while compiling.
> warnings @ client:147
> onmessage @ socket.js:41
> EventTarget.dispatchEvent @ sockjs.js:170
> (anonymous) @ sockjs.js:883
> SockJS._transportMessage @ sockjs.js:881
> EventEmitter.emit @ sockjs.js:86
> WebSocketTransport.ws.onmessage @ sockjs.js:2957
> wrapFn @ zone.js:1188
> ZoneDelegate.invokeTask @ zone.js:421
> Zone.runTask @ zone.js:188
> ZoneTask.invokeTask @ zone.js:496
> invokeTask @ zone.js:1540
> globalZoneAwareCallback @ zone.js:1566
> client:153 ./node_modules/ngx-masonry/node_modules/@angular/core/@angular/core.es5.js
> 5659:15-36 Critical dependency: the request of a dependency is an expression
>  @ ./node_modules/ngx-masonry/node_modules/@angular/core/@angular/core.es5.js
>  @ ./node_modules/ngx-masonry/ngx-masonry.es5.js
>  @ ./src/app/app.module.ts
>  @ ./src/main.ts
>  @ multi (webpack)-dev-server/client?http://0.0.0.0:0 ./src/main.ts
> warnings @ client:153
> onmessage @ socket.js:41
> EventTarget.dispatchEvent @ sockjs.js:170
> (anonymous) @ sockjs.js:883
> SockJS._transportMessage @ sockjs.js:881
> EventEmitter.emit @ sockjs.js:86
> WebSocketTransport.ws.onmessage @ sockjs.js:2957
> wrapFn @ zone.js:1188
> ZoneDelegate.invokeTask @ zone.js:421
> Zone.runTask @ zone.js:188
> ZoneTask.invokeTask @ zone.js:496
> invokeTask @ zone.js:1540
> globalZoneAwareCallback @ zone.js:1566
> client:153 ./node_modules/ngx-masonry/node_modules/@angular/core/@angular/core.es5.js
> 5675:15-102 Critical dependency: the request of a dependency is an expression
>  @ ./node_modules/ngx-masonry/node_modules/@angular/core/@angular/core.es5.js
>  @ ./node_modules/ngx-masonry/ngx-masonry.es5.js
>  @ ./src/app/app.module.ts
>  @ ./src/main.ts
>  @ multi (webpack)-dev-server/client?http://0.0.0.0:0 ./src/main.ts

**Comment by LucHighwalker** [comment]
well, that did indeed make it work! Kudos to you sir!

**Comment by gethinoakes** [comment]
Seems solved, thanks @thefliik
