### ISSUE TITLE
Consider updating ngx-masonry component to OnPush

### ISSUE THREAD

**Issue by thefliik** [gethinoakes/ngx-masonry#3]
So in my app I've currently updated `ngx-masonry.component` to `ChangeDetectionStrategy.OnPush` and everything seems to be working fine. This makes sense to me, because it looks like the Masonry library handles all of the DOM changes.

**Comment by amiller29au** [comment]
Change detection is inherited from the parent or containing component so there is no need to specify  ChangeDetectionStrategy from with ngx-masonry.component itself.

**Comment by thefliik** [comment]
Good to know
