### ISSUE TITLE
NgxMasonryModule is not an NgModule

### ISSUE THREAD

**Issue by vugar005** [gethinoakes/ngx-masonry#5]
Hi
Firstly, thanks for supporting project. I encounter issue which I did not have in previous angular2-masonry plugin. I follow your documentation on installing and importing the module. When I compile error happens:
```
ERROR in Error: NgxMasonryModule is not an NgModule
    at _getNgModuleMetadata (D:\vugar\Lessons-app\node_modules\@angular\compiler-cli\src\ngtools_impl.js:140:15)
    at _extractLazyRoutesFromStaticModule (D:\vugar\Lessons-app\node_modules\@angular\compiler-cli\src\ngtools_impl.js:109:26)
    at D:\vugar\Lessons-app\node_modules\@angular\compiler-cli\src\ngtools_impl.js:129:27
    at Array.reduce (<anonymous>)
    at _extractLazyRoutesFromStaticModule (D:\vugar\Lessons-app\node_modules\@angular\compiler-cli\src\ngtools_impl.js:128:10)
    at Object.listLazyRoutesOfModule (D:\vugar\Lessons-app\node_modules\@angular\compiler-cli\src\ngtools_impl.js:53:22)
    at Function.NgTools_InternalApi_NG_2.listLazyRoutes (D:\vugar\Lessons-app\node_modules\@angular\compiler-cli\src\ngtools_api.js:91:39)
    at AotPlugin._getLazyRoutesFromNgtools (D:\vugar\Lessons-app\node_modules\@ngtools\webpack\src\plugin.js:207:44)
    at _donePromise.Promise.resolve.then.then.then.then.then (D:\vugar\Lessons-app\node_modules\@ngtools\webpack\src\plugin.js:443:24)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
```
Project version:
```
"@angular/cli": "1.4.5",
"@angular/core": "^4.2.4",
"ngx-masonry":   "^0.5.4",
```
I hope you solve this problem,

**Comment by gethinoakes** [comment]
Thanks for raising the issue, unfortunately my time is pretty limited right now but I'll take a look at this when I can.

**Comment by thefliik** [comment]
@vugar005 This looks similar to the error I had with this gem (#1 ). I got around it by downloading the source and building it locally (and then everything was fine). I think the error has something to do with how it was packaged into an an npm package.

**Comment by vugar005** [comment]
@thefliik  . Thanks. But it might be temporary solution because this way is error -prone. I hope you solve this problem.

**Comment by lam-nguyen** [comment]
+1 
I have this issue when run "ng build -prod" from angular-cli. On local machine everything works fine.

**Comment by dbayonacode** [comment]
Exactly the same issue trying to build with angular CLI, please help.

**Comment by thefliik** [comment]
@lomboboo 

1. open up the main page on github: https://github.com/gethinoakes/ngx-masonry
2. click the "clone or download" button and download zip
3. In your angular app using the angular cli, generate a new module (something like `ng g module NgxMasonry`). I'm assuming that the cli will add the module into a new folder.
4. Open up the zip file you downloaded > open up src > copy the files into the modules folder you generated with angular cli, overwriting the generated `ngx-masonry.module.ts`.
5. Use the module like you would any other module in your angular project.

Make sense?

**Comment by lomboboo** [comment]
@thefliik thank you for your explanation, but I'm getting error like this:

`webpack: Failed to compile.
webpack: Compiling...
 63% building modules 130/145 modules 15 active ...ing-bar/src/slim-loading-bar.utils.jsERROR in src/masonry/ngx-masonry.component.ts(17,14): error TS2304: Cannot find name 'process'.
src/masonry/ngx-masonry.component.ts(17,38): error TS2304: Cannot find name 'process'.
`

Don't you get this error?

**Comment by thefliik** [comment]
@lomboboo Interesting, I do not get that error.

I must have introduced a bug when I submitted a PR to this package with Angular Universal support. That error is referencing this code here:
https://github.com/gethinoakes/ngx-masonry/blob/2fa6ee04f07ac687f6f2ac3517b00dd259835566/src/ngx-masonry.component.ts#L17-L20

The code checks to see if the app is running in the browser or not. Try updating the code to
```
if (!(process === undefined || (typeof process === 'object' && process + '' === '[object process]'))) {
  // is browser
  var Masonry = require('masonry-layout');
}
```
Does that fix the problem? 
If so, I'll submit a PR to this repo with the changes.

**Comment by lomboboo** [comment]
@thefliik , actually I just added 
`
    "types": [
      "node"
    ]
`
 to **compilerOptions** inside **tsconfig.json** file

**Comment by thefliik** [comment]
👍 

I have `"moduleResolution": "node",` in mine. Maybe that's why I didn't run into an error.

**Comment by juhguu** [comment]
+1
I have this issue when run "ng build -prod"

**Comment by juhguu** [comment]
@thefliik I tried this, but I also got the same error. 
`ERROR in src/app/ngx-masonry/ngx-masonry.component.ts(17,7): error TS2304: Cannot find name 'process'.
src/app/ngx-masonry/ngx-masonry.component.ts(17,40): error TS2304: Cannot find name 'process'.
src/app/ngx-masonry/ngx-masonry.component.ts(17,64): error TS2304: Cannot find name 'process'.`

**Comment by thefliik** [comment]
And did you try `lomboboo`'s solution?

**Comment by juhguu** [comment]
@thefliik yeah.
tsconfig.json:
`{
  "compileOnSave": false,
  "compilerOptions": {
    "types": [ "node" ],
    "outDir": "./dist/out-tsc",
    "sourceMap": true,
    "declaration": false,
    "moduleResolution": "node",
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "target": "es5",
    "typeRoots": [
      "node_modules/@types"
    ],
    "lib": [
      "es2017",
      "dom"
    ]
  }
}
`

package.json:
`
{
  "name": "template-selection",
  "version": "0.0.0",
  "license": "MIT",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e"
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "^5.2.0",
    "@angular/common": "^5.2.0",
    "@angular/compiler": "^5.2.0",
    "@angular/core": "^5.2.0",
    "@angular/forms": "^5.2.0",
    "@angular/http": "^5.2.0",
    "@angular/platform-browser": "^5.2.0",
    "@angular/platform-browser-dynamic": "^5.2.0",
    "@angular/platform-server": "^5.2.0",
    "@angular/router": "^5.2.0",
    "core-js": "^2.4.1",
    "imagesloaded": "^4.1.4",
    "masonry-layout": "^4.2.1",
    "ngx-slick": "^0.1.3",
    "rxjs": "^5.5.6",
    "zone.js": "0.8.16"
  },
  "devDependencies": {
    "@angular/cli": "^1.6.4",
    "@angular/compiler-cli": "^5.2.0",
    "@angular/language-service": "^4.2.4",
    "@types/jasmine": "~2.5.53",
    "@types/jasminewd2": "~2.0.2",
    "@types/node": "~6.0.60",
    "codelyzer": "~3.2.0",
    "jasmine-core": "~2.6.2",
    "jasmine-spec-reporter": "~4.1.0",
    "karma": "~1.7.0",
    "karma-chrome-launcher": "~2.1.1",
    "karma-cli": "~1.0.1",
    "karma-coverage-istanbul-reporter": "^1.2.1",
    "karma-jasmine": "~1.1.0",
    "karma-jasmine-html-reporter": "^0.2.2",
    "protractor": "~5.1.2",
    "ts-node": "~3.2.0",
    "tslint": "~5.7.0",
    "typescript": "2.4.2"
  }
}
`

**Comment by thefliik** [comment]
And you tried the 
```
if (!(process === undefined || (typeof process === 'object' && process + '' === '[object process]'))) {
  // is browser
  var Masonry = require('masonry-layout');
}
```
Update?

Well then you could yank out the conditional entirely. It is only there to support Angular Universal, so if you don't need that you should be A-OK. I am surprised that you're drawing an error when you simply try to test `process === undefined` though. Apparently I'm not super familiar with Javascript, because I didn't think that would ever draw an error.

**Comment by juhguu** [comment]
@thefliik yes, a tried this. And yes, I need the Angular Universal. 😆

**Comment by thefliik** [comment]
@juhguu, I just tested the following, and it seems to work. It may solve the issue for you
```
var masonryConstructor: any = undefined;

export class NgxMasonryComponent implements OnInit, OnDestroy {

  ngOnInit() {
    if (isPlatformBrowser(this.platformId) && masonryConstructor === undefined) {
      masonryConstructor = require('masonry-layout');
    }

    // Initialize Masonry
    if (isPlatformBrowser(this.platformId)) {
      this._msnry = new masonryConstructor(this._element.nativeElement, this.options);

```

Obviously there's a lot of other code around these changes that I'm not showing. Also, when trying this, remove the previous `var Masonry = require('masonry-layout');` code.

**Comment by juhguu** [comment]
@thefliik Ty. Work for me.

**Comment by dessalines** [comment]
I have this issue when using `ng serve -aot`.  The exact error message is:
```
ERROR in : Unexpected value 'NgxMasonryModule in .../node_modules/ngx-masonry/ngx-masonry.js' imported by the module 'AppModule in .../src/app/app.module.ts'. Please add a @NgModule annotation.
```

**Comment by thefliik** [comment]
@dessalines actually you have issue #1, which was incorrectly closed.

**Comment by Shailu4u** [comment]
I created a new Angular 5 masonry module - https://github.com/Shailu4u/ng-masonry-grid
Works with AOT.

**Comment by gethinoakes** [comment]
@vugar005 @lam-nguyen @dbayonacode @lomboboo @juhguu @dessalines 

 I've updated the whole package now so this should no longer be a problem, please try installing the latest version using NPM (v1.0.0) and let me know if you wouldn't mind. 

Sorry it took so long :)
