### ISSUE TITLE
Remove console.log messages

### ISSUE THREAD

**Issue by LongPotato** [gethinoakes/ngx-masonry#6]
Hi,

I just installed this library through npm, and I see this version (0.5.4) still prints out console.log messages even though they are commented out in the source code.

Can you push the update? Thanks!

![consolg-log](https://user-images.githubusercontent.com/9331685/33970197-8e0bca42-e026-11e7-9a91-732f29897427.PNG)

**Comment by gethinoakes** [comment]
should be fixed in https://github.com/gethinoakes/ngx-masonry/releases/tag/v1.0.1
