### ISSUE TITLE
Failed to execute 'removeChild' on 'Node'

### ISSUE THREAD

**Issue by LongPotato** [gethinoakes/ngx-masonry#7]
I am experiencing this issue when using useImageLoaded:
![error-cslog](https://user-images.githubusercontent.com/9331685/33970899-7455fa92-e02a-11e7-9d04-14d84096c69b.PNG)

My page makes an API call to add additional items into in the list when the user scrolls down to the bottom the page.

This issue occurs when the number of items inside the list is big.

I think it's similar to this issue: https://github.com/jelgblad/angular2-masonry/issues/57

**Comment by dbayonacode** [comment]
I had the same issue and I fixed it making sure that the method which add additional items is called once after a specified number of milliseconds (1 sec). I am using ngx-infinite-scroll library for adding extra items and setting the infiniteScrollThrottle attribute to define the number of millisecond to throttle. Hope it helps.
