### ISSUE TITLE
Dynamic responsiveness

### ISSUE THREAD

**Issue by robertzxz** [gethinoakes/ngx-masonry#88]
So when I open the page in a small window and start making it bigger the responsiveness of my layout works perfectly
BUT when I do it in a opposite direction it doesn't. When I refresh the page the layout goes back to normal.
Any ideas?

**Comment by robertzxz** [comment]
So since I cant find a way to initialize masonry to manually call the layout method, i tried changing the boolean of updateMasonryLayout variable to initiate it but it wont call it?

**Comment by wynfred** [comment]
Hi, this lib doesn't have a built in function to do that. You'll need to listen to the change of window size and call the layout function.
`updateMasonryLayout` should trigger the layout when its value changes, or you can use this to get a reference of the masonry object.
` @ViewChild(NgxMasonryComponent) masonry: NgxMasonryComponent;`
