### ISSUE TITLE
Dynamic loading of masonryItems

### ISSUE THREAD

**Issue by VargaBDaniel** [gethinoakes/ngx-masonry#89]
I've been trying to create a dynamic gallery that uses *ngFor to loop through an array, but I can't seem to get it working. The setup works perfectly when I use a hardcoded amount of elements, but as soon as I get *ngFor into the mix the elements appear one in each row.
I feel like this feature should be supported so I'm pretty sure I'm doing something wrong.

Template:
```
<ngx-masonry [options]="masonryOptions">
  <div
    *ngFor="let item of array"
    class="masonry-card"
    style="
      width: 180px;
      height: 260px;
      background-color: black;
      border-radius: 15px;
    "
  ></div>
</ngx-masonry>
```

TS:
```
export class MasonryLayoutComponent implements OnInit {
  public array = [1, 2, 3, 4, 5, 6];
  public masonryOptions: NgxMasonryOptions = {
    itemSelector: '.masonry-card',
    columnWidth: 180,
    gutter: 30
  };

  constructor() {}

  ngOnInit(): void {}
}
```

**Comment by wynfred** [comment]
Seems like you're missing the directive `ngxMasonryItem` in the `div` item.

**Comment by VargaBDaniel** [comment]
I am aware of that and I tried adding it, but then the items don't even get loaded into the DOM.

**Comment by wynfred** [comment]
Well, then something else is wrong. Put it on stackblitz if you can so I can take a look. Or you can check the demo repo and see if you can figure it out.
