### ISSUE TITLE
Issue with setting one brick as a two column brick

### ISSUE THREAD

**Issue by AhsanAyaz** [gethinoakes/ngx-masonry#9]
First of all, thanks for moving to `ngx` 👍 
The issue I'm facing is that I want the first card to take 2/3 of the available space. But it is not happening. In fact, if you try to give 2 columns to any of the bricks it won't work. Do you know a workaround we could have? 
Here's a [Plunker](https://plnkr.co/edit/415xygMYZquZeaeulX8V?p=preview) explaining the issue.

Attaching an image too.
![screen shot 2018-01-11 at 2 13 30 pm](https://user-images.githubusercontent.com/9844254/34817397-a4b36196-f6d9-11e7-85d2-376b56146a7a.png)

**Comment by thefliik** [comment]
@AhsanAyaz it doesn't look like your code has a _grid sizer_ as explained in the [masonry docs](https://masonry.desandro.com/layout.html) (response layout section). See if that fixes it.

**Comment by AhsanAyaz** [comment]
Already tried. Doesn't fix it.

**Comment by thefliik** [comment]
So I got plunkr working on my computer and decided to run your example again. As I suspected, this is user error. NgxMasonry works fine, you were not following the [masonry instructions](https://masonry.desandro.com/layout.html).

Working plunkr can be seen here: https://plnkr.co/edit/JF0LvCooeqtHOcHE7qyG

**Comment by gethinoakes** [comment]
Thanks @thefliik, closing.
