### ISSUE TITLE
Angular 13 Support

### ISSUE THREAD

**Issue by Destreyf** [gethinoakes/ngx-masonry#90]
Would it be possible to get an update to support angular 13?

**Comment by juanmafont** [comment]
Yes, please, add support to angular 13.

**Comment by AlonsoK28** [comment]
```
PS D:\Documents\dev\amazmation-app-2> npm install ngx-masonry masonry-layout --save
>>
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: amazmation-app-2@1.0.0
npm ERR! Found: @angular/common@13.1.1
npm ERR! node_modules/@angular/common
npm ERR!   @angular/common@"~13.1.0" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer @angular/common@"^12.0.0" from ngx-masonry@12.0.0
npm ERR! node_modules/ngx-masonry
npm ERR!   ngx-masonry@"*" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!
npm ERR! See C:\Users\Alons\AppData\Local\npm-cache\eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Alons\AppData\Local\npm-cache\_logs\2021-12-15T20_46_15_388Z-debug.log
```

**Comment by AlonsoK28** [comment]
> ```
> PS D:\Documents\dev\amazmation-app-2> npm install ngx-masonry masonry-layout --save
> >>
> npm ERR! code ERESOLVE
> npm ERR! ERESOLVE unable to resolve dependency tree
> npm ERR!
> npm ERR! While resolving: amazmation-app-2@1.0.0
> npm ERR! Found: @angular/common@13.1.1
> npm ERR! node_modules/@angular/common
> npm ERR!   @angular/common@"~13.1.0" from the root project
> npm ERR!
> npm ERR! Could not resolve dependency:
> npm ERR! peer @angular/common@"^12.0.0" from ngx-masonry@12.0.0
> npm ERR! node_modules/ngx-masonry
> npm ERR!   ngx-masonry@"*" from the root project
> npm ERR!
> npm ERR! Fix the upstream dependency conflict, or retry
> npm ERR! this command with --force, or --legacy-peer-deps
> npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
> npm ERR!
> npm ERR! See C:\Users\Alons\AppData\Local\npm-cache\eresolve-report.txt for a full report.
> 
> npm ERR! A complete log of this run can be found in:
> npm ERR!     C:\Users\Alons\AppData\Local\npm-cache\_logs\2021-12-15T20_46_15_388Z-debug.log
> ```

Please support Angular 13 https://blog.angular.io/angular-v13-is-now-available-cce66f7bc296

**Comment by wynfred** [comment]
Sorry I'm late for this. I didn't get a chance to fully upgrade the project, so I published a new version that only removes the angular version requirement. Let me know if this works. Thanks!

**Comment by AlonsoK28** [comment]
> Sorry I'm late for this. I didn't get a chance to fully upgrade the project, so I published a new version that only removes the angular version requirement. Let me know if this works. Thanks!

I will test it 🎃

**Comment by AlonsoK28** [comment]
> Sorry I'm late for this. I didn't get a chance to fully upgrade the project, so I published a new version that only removes the angular version requirement. Let me know if this works. Thanks!

I have tried `"ngx-masonry": "^13.0.0"`  and works well in `"@angular/cli": "~13.1.1"` ☺
