### ISSUE TITLE
Could you provide the "live example" repo in README?

### ISSUE THREAD

**Issue by AlonsoK28** [gethinoakes/ngx-masonry#91]
In README you provide this repo https://github.com/wynfred/ngx-masonry-demo from this example

![image](https://user-images.githubusercontent.com/37458700/146493936-6ffeda82-fe1d-4e7f-b0ce-da58e692eb77.png)

Which does not match with this other example called as "live example" in README

![image](https://user-images.githubusercontent.com/37458700/146494064-c1307632-8547-4ddc-a239-fdb4e54fb001.png)

**Comment by wynfred** [comment]
Yeah the "live example" was written by the previous owner of this library and I don't have the access to the host. I didn't setup a new server for the updated demo app since you can always host it locally.
