### ISSUE TITLE
'ngx-masonry' is not a known element

### ISSUE THREAD

**Issue by healer1296** [gethinoakes/ngx-masonry#92]
I'm still getting this error on Ionic 5 with Angular 12. I made sure I imported NgxMasonryModule into the AppModule. I still can't find a solution to solve it. Thanks for any help
![Screen Shot 2021-12-18 at 02 05 29](https://user-images.githubusercontent.com/66637608/146596158-d2adf224-a948-4e49-b56c-445d7d3ec039.png)
!

**Comment by wynfred** [comment]
Hi, I don't have experience with Ionic 5 but it doesn't seem related. Maybe try setup the app with only ngx-masonry first, or share an online repro?
