### ISSUE TITLE
How to set containerStyle?

### ISSUE THREAD

**Issue by tbrockmoeller** [gethinoakes/ngx-masonry#94]
I'm wondering how to apply the parameter `containerStyle` correctly.

`NgxMasonryOptions` accepts only a `string`. Can you tell me an example string that should work here, please? It does not work for me.

If I check https://masonry.desandro.com/options.html#containerstyle, there should be also objects possible. Is there a reason for excepting only strings?

**Comment by wynfred** [comment]
Hi, yes you're right. It should take objects. I'll make the change in the next release. However I would recommend changing the style from the angular side. I'm not sure about your use case but you should be able to get the layout you want without using the `containerStyle`

**Comment by tbrockmoeller** [comment]
By applying a class name directly to the `ngx-masonry` element also works for me.

**Comment by tbrockmoeller** [comment]
Ok, but wasn't this issue closed a bit to fast, because the reported problem is still not solved?

**Comment by wynfred** [comment]
Well, I believe the `containerStyle` option should not be the preferred way to set element style in Angular. You should always try using the template or renderer first.
