### ISSUE TITLE
support for angular 14

### ISSUE THREAD

**Issue by rbalet** [gethinoakes/ngx-masonry#95]
I support for angular 13 & 14 would be nice.

_I can also do the transition, if owners are willing to accept the merge request_

**Comment by n4j1Br4ch1D** [comment]
its working fine on 14

**Comment by wynfred** [comment]
New build released. Let me know if there are any other issue

**Comment by rbalet** [comment]
@wynfred Thx a lot, but somehow this now not working anymore.

![image](https://user-images.githubusercontent.com/44493964/197389337-e250b924-c402-4de9-af1f-81d032940246.png)

**Comment by rbalet** [comment]
@wynfred The latest update fixed the error. 

I Just wanted to thanks you a lot for your work, much appreciated <3
