### ISSUE TITLE
Support for Angular 13 

### ISSUE THREAD

**Issue by mckemowse** [gethinoakes/ngx-masonry#96]
Seems like there is no possible way to incorporate ngx masonry in an Angular 13 project. Can you please add support? Thanks!

**Comment by n4j1Br4ch1D** [comment]
its working fine on 14

**Comment by alecrt** [comment]
@n4j1Br4ch1D yes but:

⠙ Generating browser application bundles (phase: setup)...                         Processing legacy "View Engine" libraries:
        - ngx-masonry [es2015/esm2015] (https://github.com/wynfred/ngx-masonry/)
     Encourage the library authors to publish an Ivy distribution.

**Comment by wynfred** [comment]
New build released. Let me know if there are any other issue
