### ISSUE TITLE
Angular 14 - 'NgxMasonryModule' does not appear to be an NgModule class.

### ISSUE THREAD

**Issue by glen-upton** [gethinoakes/ngx-masonry#97]
This package does not appear to work on Angular 14.  Could this package be updated to support newer versions of Angular?

Minimal reproducible example:
https://stackblitz.com/edit/angular-ivy-e9g8ky?file=src/app/app.module.ts

**Comment by wynfred** [comment]
Hi, not sure what's wrong with this online repro but I did upgraded and tested the project, which is working as expected. Does your local build have the same issue? I saw sometimes you need to  restart the server for the module to load.
